### ISSUE TITLE
Feature Request: Remove Mac Traffic Lights

### ISSUE THREAD

**Issue by 51n7** [parhamoyan/qutewindow#2]
Hi, is it possible to have an option to remove the window controls (traffic lights) in MacOS? As the OS does support this:

![2023-07-15 13 40 22](https://github.com/parhamoyan/qutewindow/assets/2657818/57cf0e44-f2f6-4991-8489-ff8c825ca6cd)

This example is using Rust but I've been trying to find a library that can create a frameless window and still keep native window controls  using Python.

Also note the following python method works but breaks the native window controls and stops the window being able to resize or move in any way.
```
self.setWindowFlags(Qt.WindowType.FramelessWindowHint)
```

**Comment by parhamoyan** [comment]
Hi, sorry for the delayed response. I've just added a function called 'hideTrafficLights' in the 'utils.py' file.
